Removing upper bounds on base dependencies
henrytill/dwergaz pull request #1
Opened 2018-06-22 17:17 UTC by xcthulhu

Currently having trouble using `dwergaz` and `haskell.compiler.ghc.841` in nix.

Removing upper bound on base seems to resolve the issue.

2018-06-22 17:21 UTC, henrytill requested changes
Could we keep the upper bounds and bump it to `4.12`?

2018-06-23 05:05 UTC, xcthulhu commented
I bumped the upper bounds as per your request.

2018-06-23 15:13 UTC, henrytill approved these changes

2018-06-23 15:14 UTC, henrytill commented
Thanks.  I'll go ahead push a new version to Hackage today or tomorrow.

2018-06-23 15:14 UTC, merged

2018-06-23 19:10 UTC, henrytill commented
Uploaded a new release to Hackage:
https://hackage.haskell.org/package/dwergaz-0.2.0.2